### ISSUE TITLE
Land Use App

### ISSUE THREAD

**Issue by pollardld** [Ecotrust/hnfp#60]
### Todo

Themes:  

 - [x] Theme management
 - [x] Theme layers
 - [x] Toggle on/off

Projects:  

 - [x] Project private to user until made public
 - [x] Add new project
 - [ ] Edit project
 - [x] Make project public
 - [x] Data points: type, site, owner, action, timeline, cost, description, objectives  
 - [x] Interaction on client
